env:
  es6: true
  node: true
extends: google
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules: 
  {
    arrow-parens: [2, "as-needed", { "requireForBlockBody": true }],
    indent: ["error", "tab", { "SwitchCase": 1 }],
    max-len: [2, { "code": 100 }],
    no-tabs: ["error", { allowIndentationTabs: true }],
    object-curly-spacing: [2, "always"],
    require-jsdoc:
      [
        "error",
        {
          "require":
            {
              "FunctionDeclaration": false,
              "MethodDefinition": false,
              "ClassDeclaration": false,
              "ArrowFunctionExpression": false,
              "FunctionExpression": false,
            },
        },
      ],
  }
