image: docker:latest

variables:
  GCP_REGISTRY_IMAGE: "gcr.io/$GCP_PROJECT_ID/$CI_PROJECT_NAME"

stages:
  - build
  - package
  - deploy

npm-test:
  stage: build
  image: node:14.14.0
  script:
    - npm i
    - npm test

docker-gcp:
  stage: package
  services:
    - docker:stable-dind
  script:
    - docker build -t "${GCP_REGISTRY_IMAGE}:${CI_COMMIT_SHA}" .
    - docker tag "${GCP_REGISTRY_IMAGE}:${CI_COMMIT_SHA}" "${GCP_REGISTRY_IMAGE}:latest"
    - echo $GCP_SERVICE_KEY | base64 -d | docker login -u _json_key --password-stdin https://gcr.io
    - docker push "${GCP_REGISTRY_IMAGE}:${CI_COMMIT_SHA}"
    - docker push "${GCP_REGISTRY_IMAGE}:latest"
  only:
    - master

cloud-run-prod:
  stage: deploy
  image: google/cloud-sdk:latest
  script:
    - echo $GCP_SERVICE_KEY | base64 -d > gcloud-service-key.json && gcloud auth activate-service-account --key-file gcloud-service-key.json
    - gcloud config set project $GCP_PROJECT_ID
    - DB_INSTANCE_CONNECTION_NAME=$GCP_PROJECT_ID:$GCP_REGION:$GCP_DB_INSTANCE
    - >
        gcloud run deploy
        $CI_PROJECT_NAME
        --image "${GCP_REGISTRY_IMAGE}:${CI_COMMIT_SHA}"
        --region $GCP_REGION
        --platform managed
        --port 8080
        --set-env-vars=CONTENT_URI=$CONTENT_URI,DB_SOCKET_PATH=/cloudsql/$DB_INSTANCE_CONNECTION_NAME
        --set-cloudsql-instances=$DB_INSTANCE_CONNECTION_NAME
        --allow-unauthenticated
  only:
    - master
